# ~/.config/yazi/yazi.toml
[mgr]
linemode = "size_and_mtime"
sort_by = "extension"

[opener]
edit = [
	{ run = 'nvim  %*', block = true,  desc = "nvim",   for = "windows" },
	{ run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]
